apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-cloudvision.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "k8s-cloudvision.name" . }}
    helm.sh/chart: {{ include "k8s-cloudvision.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "k8s-cloudvision.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "k8s-cloudvision.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        {{- range $key, $value := .Values.secretVols }}
        - name: {{ $key }}
          secret:
            secretName: {{ $value }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.exposePort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbePath }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.readlinessProbePath }}
              port: http
          volumeMounts:
            {{- range $key, $value := .Values.volMounts }}
            - name: {{ $key }}
              mountPath: {{ $value }}
            {{- end }}
          env:
            {{- range $key, $value := .Values.envVars }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
